CREATE TABLE HG_EXCEPTION_ALERT (
    SERVICE_NAME VARCHAR(255) PRIMARY KEY,
    SUBJECT TEXT,
    EMAIL_ADDRESS TEXT,
    SOURCE VARCHAR(50),
    TARGET VARCHAR(50),
    EXCLUDE_EXCEPTION_ALERT TEXT,
    VARIABLE_NAME TEXT,
    VARIABLE_PATH TEXT,
    STATUS VARCHAR(10)
);